version: "3.8"
services:
  angular-app:
    container_name: angular-app-container
    build: ./angular-todos-2
    ports:
      - "4200:4200"
    volumes:
      - "./angular-todos-2:/app"
      - "/app/node_modules"
  json-server:
    container_name: json-server
    build: ./json-server
    ports:
      - "3000:3000"
    volumes:
      - "./json-server:/app"
      - "/app/node_modules"
  server:
    container_name: demo-server
    build: ./demo-server
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./demo-server:/home/app
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecret
      - SPRING_BOOT_DEVTOOLS_RESTART_ENABLED=true
